version: "2.2"
services:
  valheim-service:
    container_name: valheim
    build:
      context: .
    image: valheim/custom
    restart: always
    ports: 
      - "2456-2457:2456-2457/udp"
    volumes:
      - ./valheim-data:/home/steam/valheim-data
  